-
  name: 'Manifest'
  uriPattern: 'manifest.json'
  defaults:
    '@package': 'DIU.Neos.PWA'
    '@controller': 'Manifest'
    '@action': 'index'
  httpMethods: ['GET']
  appendExceedingArguments: FALSE
