DIU:
  Neos:
    PWA:
      Workbox:
        globDirectory: 'Web/'
        globPatterns:
#          - '_Resources/Static/Packages/{DIU,Sitegeist}.*/**/*.{js,css,gif,jpg,svg,png,webp,woff,woff2}'
        globFollow: true
        swDest: 'Web/sw.js'

#        runtimeCaching:
#          -
#            # Match any request that ends with .png, .jpg, .jpeg or .svg.
#            urlPattern: /\.(?:png|jpg|jpeg|svg)$/
#
#            # Apply a cache-first strategy.
#            handler: 'CacheFirst'
#
#            options:
#              # Use a custom cache name.
#              cacheName: 'images'
#
